version: 2.1
jobs:
  test:
    parameters:
      ruby_version:
        type: string
    docker:
      - image: circleci/ruby:<< parameters.ruby_version >>
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rake
workflows:
  build_and_test:
    jobs:
      - test:
          name: "Test against Ruby 2.4"
          ruby_version: "2.4.9"
      - test:
          name: "Test against Ruby 2.5"
          ruby_version: "2.5.7"
      - test:
          name: "Test against Ruby 2.6"
          ruby_version: "2.6.5"

